/**
 * @file    modbus_test.c
 * @brief   Modbus testing functions
 * @author  Generated by Copilot
 */

#include "modbus_test.h"
#include "modbus_device.h"

/* Private variables ---------------------------------------------------------*/
static uint32_t test_counter = 0;
static uint16_t test_value = 0;

/* Exported functions -------------------------------------------------------*/

/**
 * @brief  Initialize Modbus test functions
 * @param  None
 * @retval None
 */
void Modbus_Test_Init(void)
{
    // Set initial test values
    Modbus_Device_SetRegister(0, 0x1234);  // 40001: Test sensor 1
    Modbus_Device_SetRegister(1, 0x5678);  // 40002: Test sensor 2
    Modbus_Device_SetRegister(9, 0x0001);  // 40010: Status (bit 0 = ready)
    Modbus_Device_SetRegister(11, 0x0100); // 40012: Firmware version 1.0
}

/**
 * @brief  Update test values periodically
 * @param  None
 * @retval None
 */
void Modbus_Test_Update(void)
{
    test_counter++;

    // Update test sensor values every 100 cycles
    if (test_counter % 100 == 0)
    {
        test_value++;
        // Modbus_Device_SetRegister(0, test_value);     // 40001 - Commented out to preserve test data
        // Modbus_Device_SetRegister(1, test_value + 1); // 40002 - Commented out to preserve test data
        // Modbus_Device_SetRegister(2, test_value + 2); // 40003 - Commented out to preserve test data
        // Modbus_Device_SetRegister(3, test_value + 3); // 40004 - Commented out to preserve test data
    }

    // Update status register
    uint16_t status = 0x0001; // Bit 0: Ready
    if (test_counter % 200 == 0)
    {
        status |= 0x0002; // Bit 1: Data updated
    }
    Modbus_Device_SetRegister(9, status); // 40010

    // Simulate temperature reading (25.00°C = 9472) - Commented out to preserve test data
    // Modbus_Device_SetRegister(4, 205); // 40005

    // Simulate humidity reading (65.00% = 25856) - Commented out to preserve test data
    // Modbus_Device_SetRegister(5, 652); // 40006
}