/**
 * @file    modbus_test.h
 * @brief   Modbus testing functions header
 * @author  Generated by Copilot
 */

#ifndef __MODBUS_TEST_H
#define __MODBUS_TEST_H

#ifdef __cplusplus
extern "C"
{
#endif

    /* Exported functions -------------------------------------------------------*/
    void Modbus_Test_Init(void);
    void Modbus_Test_Update(void);

#ifdef __cplusplus
}
#endif

#endif /* __MODBUS_TEST_H */