/**
 * @file    modbus_init.h
 * @brief   Modbus initialization header
 * @author  Generated by Copilot
 */

#ifndef __MODBUS_INIT_H
#define __MODBUS_INIT_H

#ifdef __cplusplus
extern "C"
{
#endif

#include "modbus.h"

    /* Exported variables -------------------------------------------------------*/
    extern uint8_t modbus_rx_buffer[256];
    extern uint8_t modbus_tx_buffer[256];

    /* Exported functions -------------------------------------------------------*/
    void Modbus_Init(void);
    void Modbus_Process(void);
    mbus_t Modbus_GetContext(void);

#ifdef __cplusplus
}
#endif

#endif /* __MODBUS_INIT_H */