/**
 * @file    uart_callbacks.h
 * @brief   UART callback functions header
 * @author  Generated by Copilot
 */

#ifndef __UART_CALLBACKS_H
#define __UART_CALLBACKS_H

#ifdef __cplusplus
extern "C"
{
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"

    /* Exported functions -------------------------------------------------------*/
    void UART_Callbacks_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* __UART_CALLBACKS_H */